language: ruby

os:
  - linux

addons:
  apt:
    packages:
      - python

env:
  - TEST_CMD="rspec -f json -o rspec.json"
  - TEST_CMD="ruby mini_tester.rb" OPT="--framework minitest"
  - TEST_CMD="ruby test_unit_all.rb --runner=xml --output-file-descriptor=1 | tee -o test_unit.xml"
script:
  - $TEST_CMD
after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py | python - $OPT